### ISSUE TITLE
xlsx file Open with issue Firefox only

### ISSUE THREAD

**Issue by charul2007** [eligrey/FileSaver.js#139]
I am using excel-builder.js library to create the excel data and FileSaver.js to save this file.
Below is my code for saving: 

testDataWorkbook.addWorksheet(testData);

saveAs(ExcelBuilder.createFile(testDataWorkbook, {
    type: "blob"
}), "test.xlsx");

Which works just fine in chrome and IE.
The problem I am getting with Firefox is while doing "Open with" the file which gets created is 
"test.xlsx.zip" which then throws a warning of different format than specified by the file extension.

Any help on the issue is much appreciated.

**Comment by eligrey** [comment]
Hmm, that seems to be from Firefox checking magic numbers and realizing it's a zip (xlsx is a zip file filled with a bunch of XML) even though there are other zip-contained formats like the one you're using. I suggest that you also file this issue on https://bugzilla.mozilla.org/ and link to the issue here after filing it there, so I can keep up with the issue as well.

**Comment by davidda** [comment]
I ran into the same issue and was able to resolve it. It is neither an issue with FileSaver nor Firefox. Firefox behaves correctly, because the file you are trying to save actually IS a zip file. ExcelBuilder just returns JSZip's output, which unsurprisingly has the zip mime type.

Try this instead:
```
var dataArray = ExcelBuilder.createFile(testDataWorkbook, {type: "uint8array"});
var blob = new Blob([dataArray], { type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" });
saveAs(blob, "test.xlsx");
```

**Comment by charul2007** [comment]
Sorry for the delayed reply. I updated the excel export code to use the type: "uint8array". Works perfectly on FF/Chrome/IE. Thanks again.

**Comment by arshad806** [comment]
Hi,
anyone help me we used table to excel in  jQuery .when table inside a table excel file get table and go to next row ...my issue is when we make table inside td excel file make table inside this td .
