### ISSUE TITLE
Saving huge files ( 2GB + )

### ISSUE THREAD

**Issue by DannyZB** [eligrey/FileSaver.js#163]
I would like to implement, if possible , a multi-connection downloader in HTML5..
To do that for extremely large files , it needs to download in chunks and join them in a whole file afterwards.

Problem is > you obviously cannot store that much information in RAM ..

1.) How would you go about doing that ? is it even possible ?
2.) Would resume support be possible on browser crash ?

Thanks !

**Comment by jimmywarting** [comment]
Your best option would be to use Filesystem API,
- it doesn't use RAM,
- and you can append chunks into a existing file. (in the beginning, end, middle or where ever)
- and when you are done you don't need to create a blob(Url) in order to download it 

    <a href="filesystem:http://localhost/temporary/largefile.zip" download="largefile.zip"> click to download </a>

I know this is a Blink only browser solution. But its also the only way you can save such large files

**Comment by DannyZB** [comment]
Thanks for the answer

https://github.com/ebidel/idb.filesystem.js
Seems to be a polyfill-ish thing for firefox

Time to look for polyfills :D

**Comment by jimmywarting** [comment]
That is a polyfill that uses IndexedDB.
IndexedDB dosen't support appending chunks to a blob or file. That pollyfill will read the file from the database construct a new blob with the previous file+chunk and override the previous file. Don't know if its so RAM effective as to being able to save 2GB of data

Anyway here is something i have been worked on that might be of interest to you
https://gist.github.com/jimmywarting/e1f2dd369e2098b4881b

It contains some source code of how to use multiple AJAX threads to download a file in different versions  methods I could think of.
Some keywords to sum it up would be: ajax, xhr, fetch, stream, pipe, RAM, filesystem API, large download, up to 6-12 times faster download (incase website throttles the speed)

PS more download thread dosen't mean it downloads faster...

**Comment by DannyZB** [comment]
Wow everyone in this industry has something against proper use of RAM.

"PS more download thread dosen't always mean it downloads faster...
(By threads i mean multi-connection)"
The big problem with this method is going to be the move to HTTP/2.
In HTTP/2 / SPDY multiple download sources only use the same connection , thus negating the improvement in speed from multiple connections.

From what I see it's chrome only, correct ?
get chunks from XHR > stitch together to a file with the filesystem API.

**Comment by jimmywarting** [comment]
Yea, it "stitch" a file together using ajax.
My code dosen't use http2 

And its not chrome only... Its blink only wich means chrome and opera.

**Comment by DannyZB** [comment]
Opera is a great browser .. but lets not pretend anyone uses it :)

http2 isn't on the client side, it's a server protocol.
If the server is HTTP/2 ( and they are going to be soon ) chrome automatically defaults to it, and the same for all other browsers.

If you want the speed boost of multiple connections put a remark for users to make sure their server has SPDY and HTTP/2 disabled.

I'll give it a look, see if I can stitch something up

**Comment by jimmywarting** [comment]
If you can give me any feedback/improvment on my code i would be happy to see it. Just seeing what you came up with is interesting ;)

**Comment by jimmywarting** [comment]
Opera might be the first one to solve the blob file size limit
https://www.chromestatus.com/features/4956772716511232

**Comment by jimmywarting** [comment]
Something new and awesome has came up: [StreamSaver.js](https://github.com/jimmywarting/StreamSaver.js)

**Comment by DannyZB** [comment]
Sounds interesting, but how cross-browser is it?
and how did they do it anyway?

I was already looking into joining several other providers to create binary extensions for all browsers to create a pseudo-standard.

Their code is only 80 lines, have you tried plugging it into FileSaver?

**Comment by eligrey** [comment]
@jimmywarting Awesome! I was reading about the new streams spec at <https://jakearchibald.com/2016/streams-ftw/> recently, and it's surprising to see that you already have something in the works.

**Comment by jimmywarting** [comment]
I have been thinking a lot about FileSaver.js and how cool it would be if it had a asynchronous way to save files with no file size limit, I knew long before that it would be possible with service worker + fetch api

fetch api allows to respond with a bytestream generated from client side
So it has always been possible to create a `new Response(stream)` from userMedia but there was no way to get the stream in to service worker until now

So i had to make it.
I was thinking if it could be a sub module to FileSaver.js or anything like that, but didn't want to include it here since its so new and all diffrent

**Comment by eligrey** [comment]
I'd definitely be up for merging your code into FileSaver.js as the "2.0" version, once it's closer to completion.

**Comment by jimmywarting** [comment]
@DannyZB 
> but how cross-browser is it?

00.5% maybe (needs to be enabled by a flag), it still very new but once chrome ships v52 then [60%](http://gs.statcounter.com/) of the browser will have it. Maybe will be ~15 weeks from now. Heck even firefox may have shipped it by then also, hopefully.

> and how did they do it anyway?

There is no "they" it's only me atm. And I solved it by using service worker + fetch api + the new stream api. And also MessageChannel (but that is less important)

I also want to give some credit to @muaz-khan for building the [Screen Capturing
](https://chrome.google.com/webstore/detail/screen-capturing/ajhifddimkapgcifgcodmmfdlknahffk) for giving access to the screen as a stream

**Comment by jimmywarting** [comment]
@eligrey I have recently found a way around the HTTPS so it works on http:// and file://

**Comment by chuanlin2018** [comment]
Hi, I am currently working on a project that need to use Angular 6 to download huge files and display the progress and status while downloading. I know httpclient can provide the progress but don't know how to stream the data to local disk. Can streamSaver work with Angular 6?

**Comment by chuanlin2018** [comment]
Thank you so much for pointing me to the right direction. I am new to indexeddb. Will do some research on how Angular 2+ download file through indexeddb. If you happen to know a working sample please advise. Much appreciated.

**Comment by egortsaryk9** [comment]
> The only way for large files at the moment is running a buffer through indexeddb, thus making it disk based, then starting a download from that buffer.

@DannyZB 
May I ask you how to start download process from the IndexedDB for a file that is split in chunks ? Is there a way to download a file to user's filesystem from the indexeddb-buffer progressively in order to not overflow the RAM ? I am aware that we can concatenate all the chunks into a single Blob to save it via ObjectURL (and that's what the FileSaver does afaik), but this cannot be used for large files due to RAM limits.
Could you provide any links to existing implementations ? I thought it is not possible because of lack of api to native filesystem

**Comment by jimmywarting** [comment]
it's theoretical possible to save lots of chunks in a indexedDB that's saved as a blob or a file (not as typed arrays)
the blobs will be stored on the disk and be treated as a file somewhere on the harddrive.
later when you get the blob from indexeddb again you will have a reference to that blob instead of having everything in the memory. a blob is just a container of stuff you don't know what it is. it could be data from memory or it could be data from another blob or a file on the dish

and when you concatenate all chunks it will become a new blob with many references /w different offsets. 

See this chrome representation of what a blob is https://stackoverflow.com/a/39257921/1008999

---

- you could test this method using a file input with multiple select
- select a few large files and make a new blob out of all files
- the memory should not increase with the amount of data
- the new blob should only have pointers to the large files on the disk (internally)

**Comment by jimmywarting** [comment]
but ofc using streamsaver instead would be a tremendous help instead of using indexeddb
it now has a blob fallback for safari and works in newest edge, firefox and blink (chrome, opera, brave)

**Comment by egortsaryk9** [comment]
@jimmywarting  Thank you a lot for your clarification, your Blob representation from the StackOverflow answer is very helpful. I see the point now and will make some tests.
I've looked into StreamSaver a bit, it looks really interesting. But I'm not sure yet that I can use it in our app since it uses github static page as `mitm` to initiate server response. Our product has strict security rules, and most likely such `mitm` will be an issue. However, I like the concept in general and will try to play with it

**Comment by DannyZB** [comment]
@jimmywarting How are we on resume from this?
An indexeddb implementation enables resumes. Any way to make that happen with streamsaver?

Now with browser maturity, im starting tests on it again. Wonder how far it can stretch

**Comment by jimmywarting** [comment]
> But I'm not sure yet that I can use it in our app since it uses github static page as mitm to initiate server response. Our product has strict security rules, and most likely such mitm will be an issue. 

@egortsaryk9 you could always host it yourself on your own domain
to configure streamsaver to use an other mitm you can specify `streamSaver.mitm = url`


> How are we on resume from this?
>An indexeddb implementation enables resumes. Any way to make that happen with streamsaver?
>
> Now with browser maturity, im starting tests on it again. Wonder how far it can stretch

I don't think i will implement a indexedDB solution into streamSaver. the intention with streamsaver is to write stuff directly to the hard drive and giving a native experience to the browser interface where you are able to pause, resume and abort as well as showing a progress and how much you have downloaded.

all doe you won't be able to resume a broken/aborted download

**Comment by DannyZB** [comment]
* all doe you won't be able to resume a broken/aborted download

I didn't intend to save this to Indexeddb. That misses the point.

1. As far as broken/aborted, is there a possibility for a user to choose an existing file on his computer to continue?

2. What about computer restarts? Any way to resume after those?


What it looks like to me, at this point, is this is only going to keep going as long as the browser is up.

**Comment by jimmywarting** [comment]
> As far as broken/aborted, is there a possibility for a user to choose an existing file on his computer to continue?

The only way to do that is by using the new Native FileSystem api
you have the ability to select a folder or a existing file and write to the file /w an offset

> What about computer restarts? Any way to resume after those?

nope, only the new native filesystem api can do that.

> What it looks like to me, at this point, is this is only going to keep going as long as the browser is up.

yepp, that's correct. like with StreamSaver and FileSaver the hole goal is to save data that has been generated on the client side. for anything else coming from a server/cloud the best option has/will always be to send a `content-disposition`-attachment header to force the browser to save a file.

if you want to have something that handles downloads from a server that can break the download or you would temporary be offline then the best thing would be to use [background-fetch](https://developers.google.com/web/updates/2018/12/background-fetch). then you can even download the files without having the browser open as it will use some native download mananger like the one you would have on the android phone.

then you get an event when the download is complete, you can decide what you want to do with this file - you could trigger something that opens the file but you would set the content-disposition header to force it to save

**Comment by DannyZB** [comment]
Alright, that sounds clear.
Have you looked into the milestones for browsers wanting to implement this? Is it something that is going to be implemented?

Links to discussions about this on Firefox/Chromium would help a lot in tracking this


To make things clear for anyone reading later:
1. FileSaver and StreamSaver can only run while a browser window is open with their page
2. They do not support resume and cannot support resume after they have closed
3. The only way to support it is with new APIs that are not yet implemented anywhere fully.
