### ISSUE TITLE
Few errors where !==/=== should be used in place of !=/==

### ISSUE THREAD

**Issue by evilaliv3** [eligrey/FileSaver.js#207]
Few point of the libraries seems to use wrong javascripts comparisons: https://codeclimate.com/github/eligrey/FileSaver.js/FileSaver.js#bugrisk

This on certain conditions may affect browser compatibilities

![screenshot from 2016-03-19 01 14 52](https://cloud.githubusercontent.com/assets/217034/13895147/30a16cea-ed70-11e5-8f7b-cd8a33297bc7.png)

**Comment by eligrey** [comment]
I'm not sure about the logic behind `new_tab == undefined` (I didn't write that line), but the author could have intended to also catch `null`. This may or may not cause problems. I don't have Safari, so I have no idea.

**Comment by jimmywarting** [comment]
Well, if the popup was opened successfully then you would get back a new window object - that will always be the case upon success, 

Not sure if all browser return undefined maybe null too in some odd case, but anyway it's enough to check falsy values here, since the success will always be window

Since it's the last "if nothing else works statement" then all that remains is to open the page in the current window so regardless if it's safari or not all browser that does not pass all the other feature should fall into this statement as well

so `if(!new_tab)` would be significant
