### ISSUE TITLE
Save As dialog on Chrome won't launch if another FileSaver "Save As..." dialog is pending

### ISSUE THREAD

**Issue by bholyfield** [eligrey/FileSaver.js#214]
Not sure if this is a bug in Chrome or FileSaver. The issue occurs on Chrome when it is configured to ask the user where to save downloaded files to. If you have two simultaneous FileSaver web workers running and one goes to save a file, the "Save As..." dialog correctly appears.  While that dialog is pending (no location chosen yet), if the 2nd thread goes to save a file the dialog does not (and will never) appear.  Chrome shows the download pending with 100% progress but there is no way to save the file.  

You can reproduce this on the demo page by adding code that triggers the click() event on all of the "Save" buttons at the same time.  Any thoughts on how to fix?

**Comment by henninghov** [comment]
I am having the same issue! It does not seem to be an issue in Chrome on PC as all the Save dialogues are stacked on top of each other. But in Chrome on Mac the save dialogue is not opened util you close the first - the files are downloaded but as stated by @bholyfield the files are not accessible.

**Comment by jimmywarting** [comment]
What i did on my app was to zip all the things that needed to be downloaded first with [JSZip](https://stuk.github.io/jszip/) then i saved that. Perhaps not what you are looking for, but removes the hassle of showing multiple "Save as... window"

**Comment by Ruffio** [comment]
@bholyfield is this still an issue or has Google fixed it?

**Comment by larrydahooster** [comment]
@Ruffio from what I experienced today, Chrome comes up with a warning: 
![screen shot 2017-09-06 at 12 09 39](https://user-images.githubusercontent.com/4989851/30106642-6a8a48c2-92fc-11e7-8266-52159f2160cd.png)

Still wondering if it is usable in production cause I don't know if the users are able to chose the right decision here. If they pick wrong they might wonder why a download does not get triggered under certain circumstances.

**Comment by Ruffio** [comment]
Is this still an issue? When reading the aboe, it looks like this is the implementation/restriction of Chrome that can't be circumvented. As suggested above, consider to save the files into a zip file in order to avoid this issue.

**Comment by larrydahooster** [comment]
For me it was a showstopper for this reasons:

1. You can't access the permissions in chrome. If a user blocked it, you can't offer fallbacks. Telling a client that he needs to access his browser permissions in order to get his downloads does not work well for me.

2. The mentioned 'zip-file' fallback does not work for me as we allow multiple asynchronous file generations at the same time. Even making them synchronous in a queue style does not work, cause you have no control over the file-download-dialogue. So you don't get the correct callbacks that you would need to start the next job in queue after one file finished it's interaction with the download-dialogue.
