### ISSUE TITLE
Incorrect Byte Order Mark in auto_bom()

### ISSUE THREAD

**Issue by nyditot** [eligrey/FileSaver.js#219]
As defined in http://www.w3.org/TR/REC-xml/#sec-guessing shouldn't the automatically prepended BOM for UTF-8 be "EF BB BF" rather than "EF FF"?  The latter is the appropriate BOM for UTF-16BE encoding.

Also it would be nice to extend the auto BOM feature for other encodings such as UTF-16, etc.

**Comment by eligrey** [comment]
Hm, yeah seems like I should be using `EF BB BF`. I'll look into this further soon

**Comment by evilaliv3** [comment]
@eligrey i confirm that this bug is affecting GlobaLeaks also.

Correct me if i'm not wrong, but i think that you could clarify better on the Readme that this feature is generally needed only when creating the file clientside, but when the filesaver library is used simply for saving a file corresponding to a previous file upload the autobloom feature is unnecessary and would 
cause always failures because downloaded_file will be always different from the uploaded_file.

\cc @fpietrosanti @NSkelsey

**Comment by eligrey** [comment]
@evilaliv3 You shouldn't run into this problem at all unless you are specifying `;charset=utf-8` on your files. There is no reason to specify this parameter on binary files.

**Comment by eligrey** [comment]
@nyditot Apparently in UCS-2 \uFEFF is actually the UTF-8 BOM, so I'm reverting this change.
