### ISSUE TITLE
Not opening file on iOS and Firefox

### ISSUE THREAD

**Issue by racon-am** [eligrey/FileSaver.js#249]
I am testing your demo on iOS (9.3) and Firefox (2.1). Trying to save an image/text-file etc, a new tab is opened, but the tab is blank and no file is shown/downloaded. Is this a known issue?

**Comment by iconexperience** [comment]
Are you sure about the Firefox version? AFAIK the current version is 48.0, so 2.1 appears to be a little bit outdated.

**Comment by racon-am** [comment]
The AppStore (iPad) says Firefox for iOS version 2.1, Firefox settings says version 5.0.

**Comment by jimmywarting** [comment]
Firefox for iOS is not the gecko engine. Apple only allow 3e party app to use UiWebView so it makes no since to update update the iOS version of firefox when they make any smallest change to there engine since Firefox for iOS is just but a shell to make you feel at home with firefox and making settings sync between devices. cuz in the end you are using webkit

And from my understanding only a correct mimetype can make the new tab render the file correctly

**Comment by jimmywarting** [comment]
Try changing mime type to something safari supports?
