### ISSUE TITLE
Failed to execute 'createObjectURL' on 'URL'

### ISSUE THREAD

**Issue by azain** [eligrey/FileSaver.js#252]
I am trying to use this library to push content generated by [this library ](https://github.com/evidenceprime/html-docx-js)through the browser, but I am getting this error:

` Failed to execute 'createObjectURL' on 'URL'`

Here's my code:
```
                // Generate a blob out of the passed HTML
                var docx = html2docx.asBlob(html, options);

                // Push the report to the browser, as .docx
                window.saveAs(docx, 'report.docx');
```

The `html2docx.asBlob` returns this: 
![screenshot_1](https://cloud.githubusercontent.com/assets/13228056/17643056/29397a30-615e-11e6-83b0-091136a07d6b.png)

Which isn't blob (right ?). So, what should I do ?
Thanks

**Comment by jimmywarting** [comment]
I tried this in there example page: http://evidenceprime.github.io/html-docx-js/test/sample.html
```javascript
      var contentDocument = tinymce.get('content').getDoc();
      var content = '<!DOCTYPE html>' + contentDocument.documentElement.outerHTML;
      var orientation = document.querySelector('.page-orientation input:checked').value;
      var converted = htmlDocx.asBlob(content, {orientation: orientation});
```
And it returned a blob...

judging by there API
```coffescript

  generateDocument: (zip) ->
    buffer = zip.generate(type: 'arraybuffer')
    if global.Blob
      new Blob [buffer],
        type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
    else if global.Buffer
      new Buffer new Uint8Array(buffer)
    else
      throw new Error "Neither Blob nor Buffer are accessible in this environment. " +
        "Consider adding Blob.js shim"
```

A blob is only created if `window.Blob` exist... dose it exist in your browser?
otherwise the fallback is to make a buffer - I'm going to assume yes now days... so it leads me to: are you using this in Node? Node don't have blob's so you need to us the filesystems write fn to write a buffer

Filesaver.js is only meant to work in the browser

**Comment by azain** [comment]
The problem was that html-docx-js didn't return the needed Blob but Buffer instead. To solve the problem I just called it as a script from the HTML instead of calling it as a module in Node.JS
