### ISSUE TITLE
EXCEPTION: TypeError: saveAs is not a function

### ISSUE THREAD

**Issue by josepoma** [eligrey/FileSaver.js#253]
Hi,
When I try on this with Angle 2, this message appears:

**EXCEPTION: TypeError: filesaver.saveAs is not a function**

**Comment by jimmywarting** [comment]
This belongs more to stackoverflow since this is not about FileSaver
Make sure you include [FileSaver.js](https://github.com/eligrey/FileSaver.js/blob/master/FileSaver.js) in your site in the correct way using either require/amd/import or the global 

if it's on the global (window) it's just `window.saveAs(blob, 'filename')`

**Comment by smitti24** [comment]
Hi,

I had the same problem. I just made sure that Filesaver.js is in node_modules/FileSaver/filesaver.js.

I suggest you install filesaver package again.

**Comment by WuglyakBolgoink** [comment]
install package it doesn't matter with your errors! 

Are u sure that this lib in your (global) scope (injected)? 

and please close ticket if u fixed your problem!

**Comment by r-paredes-bernal** [comment]
Fix: npm install file-saver@1.3.3 --save
Because FileSaver.saveAs method is not supported in newer version 1.3.4.

**Comment by winarmarianoj** [comment]
tanks!!!!!!!!! :)))))
