### ISSUE TITLE
File saver not working for ppt documents..

### ISSUE THREAD

**Issue by jithuakumar** [eligrey/FileSaver.js#270]
I am sending my ppt from wcf service as stream file... (i can send it as a byte[] as well if required) ,.. but not able to download it in the client side

```javascript
string filepath = "C:\\BKUP2\\Files\\xample.pptx";
String[] filename=filepath.Split('\\');            
WebOperationContext.Current.OutgoingResponse.ContentType = "application/octet-stream";
// WebOperationContext.Current.OutgoingResponse.ContentType = "application/x-mspowerpoint";
if(File.Exists(filepath))
{
   String headerInfo = "attachment; filename=" + filename[filename.Length - 1];
   WebOperationContext.Current.OutgoingResponse.Headers["Content-Disposition"] = headerInfo;
   return File.OpenRead(filepath);
}
else
{
   String headerInfo = "attachment; filename=" + "error.txt";
   WebOperationContext.Current.OutgoingResponse.Headers["Content-Disposition"] = headerInfo;
   string errortext="file not found";
   byte[] byteArray = Encoding.ASCII.GetBytes(errortext);
   MemoryStream stream = new MemoryStream(byteArray);
   return stream;
}
```

in client side

```javascript
function ServiceSucceeded2(data) {          
    var byteArray = (data);
    var blob = new Blob([byteArray], { type: "application/octet-stream" });
    var fileName = "ABA_examplereportoutppt.pptx";
    saveAs(blob, fileName);
} 
```

please help me.. if file saver cant do.. do we have any alternate option? i cannot force download from server with response object as it is wcf

**Comment by jimmywarting** [comment]
judging from the look of your code it looks like you are sending a Content-Disposition attachment header. That should be enough for just forcing the download. It's also the best method to save a file since it doesn't require any client side code and works in mostly every browser. FileSaver is only good for client side generated content and where some resource is behind a security layer so you would need ajax to authenticate

**Comment by jithuakumar** [comment]
Hi Jimmy, thank you for the update.

this is my client side ajax code.    $.ajax({
                type: "POST",
                url: "http://localhost:59793/PPTService.svc/GetPPTFromService",
                cache: false,
               
               
                contentType: "application/json; charset=utf-8",
                  success: ServiceSucceeded2
            });

there is no download option appearing even after sending the content headers... Do i miss something in the client side to get it downloaded? window.location is not working either. Appreciated if you can help on this. 

Regards,
Jithu. You can close this post if Filesaver is not an option for this.

**Comment by jimmywarting** [comment]
Hmm, okey you are doing a POST request, that way it might not work well as expected with a simple GET request. 

Best would be if you don't need FileSaver 
- Are You posting any data as well?
- dose the request require any authentication or extra request headers?
- What happens if you just navigate to `http://localhost:59793/PPTService.svc/GetPPTFromService` directly instead of fetching it with ajax?
- what would happen if you were to do this:
```html
<form method="post" target="_blank" action="http://localhost:59793/PPTService.svc/GetPPTFromService">
  <!-- all fields necessary -->
  <input type="submit">
</form>
```

If for any reason you need to make a ajax request then you need to avoid jQuery's ajax method when dealing with a binary response. javascript can't handle binary string well and jQuery response is always a json or a string - it's incapable of handling binary as the browser tries to parse the response
- use either xhr and set responseType to blob
- or use the new fetch api
```javascript
fetch(url, {method: 'post', body: data})
.then(res => res.blob())
.then(blob => saveAs(blob, "filename.ppt"))
```

**Comment by jimmywarting** [comment]
Content-Disposition header don't have any affect if you are doing a ajax request...

**Comment by jithuakumar** [comment]
Hi jimmy.. thank you for the update... :) appreciated

**Comment by jimmywarting** [comment]
How did you sölve it?

**Comment by jithuakumar** [comment]
Jimmy , as u correctly mentioned the normal form post worked!!! i triggered it from a button click event!! the issue was with jquery ajax which i was not aware about : ) thank you so much!!!
