### ISSUE TITLE
Weird bytes in empty file

### ISSUE THREAD

**Issue by iskhakovt** [eligrey/FileSaver.js#272]
Ubuntu 16.04 Firefox

```js
saveAs(new Blob([], {type: 'text/plain;charset=utf-8'}), 'test.txt');
```

downloads a file of 3 bytes instead of 0:

```cpp
symbol = getc(file);
printf("symbol '%c' %d\n", symbol, (int)symbol);
```

```
symbol '�' -17
symbol '�' -69
symbol '�' -65
symbol '�' -1 # EOF
```

Why does it happen?

**Comment by jimmywarting** [comment]
Are you using jQuery's ajax? or any other ajax where the response is not of type blob/arrayBuffer?

> The magic happens in line 5, which overrides the MIME type, forcing the browser to treat it as plain text, using a user-defined character set. This tells the browser not to parse it, and to let the bytes pass through unprocessed. - [Receiving binary data with ajax](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Sending_and_Receiving_Binary_Data#Receiving_binary_data_in_older_browsers)

Try something like this that won't make any modification to the text 
```javascript
fetch(url).then(res => res.blob()).then(blob => saveAs(blob, 'test.txt'))
```
(you could also set [responseType](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/responseType) to arrayBuffer)

Or better yet use content-disposition attachment header if possible to save a file since you have access to a server where the data comes from. It has wider support. FileSaver is mostly useful for client-side apps that generates content in the browser or where authentication is necessary and regular GET request is not enough

**Comment by iskhakovt** [comment]
I haven't got your reply.
I pass empty data: `[]` without any usage of ajax
```js
saveAs(new Blob([], {type: 'text/plain;charset=utf-8'}), 'test.txt');
```
and get 3 bytes.

**Comment by iskhakovt** [comment]
You may test it using [FileSaver example](https://eligrey.com/demos/FileSaver.js/):

Saving text:
```
symbol '�' -17 239
symbol '�' -69 187
symbol '�' -65 191
symbol 'O' 79 79
symbol 'n' 110 110
symbol 'c' 99 99
symbol 'e' 101 101
...
symbol '.' 46 46
symbol '�' -1 255
```

**Comment by jimmywarting** [comment]
hmm, okey, have you tried disableing autoBom

> Pass true for disableAutoBOM if you don't want FileSaver.js to automatically provide Unicode text encoding hints (see: byte order mark).

    saveAs(new Blob([], {type: 'text/plain;charset=utf-8'}), 'test.txt', true);

**Comment by iskhakovt** [comment]
Oh, thanks!

**Comment by eligrey** [comment]
The resulting file you are getting is a valid representation of an empty file in UTF-8. You can opt out of the auto-BOM code by either not putting `charset=utf-8` in your MIME type or by passing a third argument to saveAs, `true`.
