### ISSUE TITLE
Doesn't save file with type(jpg) in IE 11 and Edge

### ISSUE THREAD

**Issue by sandra1991tje** [eligrey/FileSaver.js#314]
It just downloads the image without the type. Is that a common problem or what am I doing wrong? Thanks

**Comment by jimmywarting** [comment]
sure you don't have the "hide extension for well known file types" preference in your os?

**Comment by michaelklopf** [comment]
Hi,

ran in a similar issue as the issue creator on IE11. We use ember-cli-file-saver, which simply provides an API to FileSaver.js. FileSaver.js is called with a Blob object like this:

`new Blob([ content ], { type: 'application/pdf' }), 'document');`

This works in Safari, Firefox, and Chrome, but IE behaves differently, it needs the .pdf at the end of the filename.

Example tested with a fiddle:

Downloads a file with name `hello`:
```
var content = "Hello world";
var filename = "hello";
var blob = new Blob([content], { type: "application/pdf" });
window.navigator.msSaveOrOpenBlob(blob, filename);
```

Downloads a file with name `hello.pdf`:
```
var content = "Hello world";
var filename = "hello.pdf";
var blob = new Blob([content], { type: "application/pdf" });
window.navigator.msSaveOrOpenBlob(blob, filename);
```

Maybe that's what caused the problem here too.
