### ISSUE TITLE
[Request] please support on saveas completion callback

### ISSUE THREAD

**Issue by dzunglht** [eligrey/FileSaver.js#335]
we love your great work, please support on saveas completion callback
Many thanks

**Comment by jimmywarting** [comment]
Not possible

**Comment by Ruffio** [comment]
Presse close this issue.

**Comment by jimmywarting** [comment]
There is no way to detect if a file was saved or not. And the task is synchronous. even if it might not look like it.

It would just look like

```js
save(file, cb) {
  click_the_link( generate_link(file) )
  cb() // instant callback
}
```

We have to wait until [WICG/writable-files](https://github.com/WICG/writable-files) gets implemented in other browsers

**Comment by jimmywarting** [comment]
Btw, StreamSaver.js takes another approach. when a user save something it will generate a uniq link that utilities the stream api together with fetch and service worker - i think it's a bit hacky. 

- The stream can pull more data when it's asking for more. 
 - so technically it's possible to know if the user have begun saving the file to some destination
   - however. the saveAs dialog will not appear until you write a bit of data to the stream first, so you can only detect that if the user have chosen a destination after `x` bytes...
- the stream also has a way of telling when the stream successfully closes (reached the end) so a callback could technically be implemented.
- it's also possible to know when a stream back pressure (when it has to big buffer) meaning: you can also detect when a user pause the process
- it also has a cancelation event but it's not fired by the download manager. I have reported this as a bug.

so you could have something like this (just speculations)
```js
saveAs(stream || blob || typedArray || arrayBuffer || {
  onStart () {
    // a link has been clicked, start to
    // write some data to initiate the save dialog
    return x /* blob chunk, typed array, ArrayBuffer, string */
  },
  onPull (progress) {
     if (progress.totalBytesWritten && called.pull(10).times) {
       // probably means user is writing something to the disk
     }
     // download mananger asking for more data, Write data
     return x /* blob chunk, typed array, ArrayBuffer, string */
  },
  onProgress (evt) {
    evt.writtenBytesInChunk
    evt.totalBytesWritten
  },
  onCancel (evt) {
    // user aborted the download
    // but is never triggerd
  },
  onDone () {
    // Successfully closed 
  }
}, 'file name.txt')
```

this only works in chrome atm, Edge might work too, have no way of testing.
but it's too complicated to map a readable/writable stream across main thread to a service worker with postMessage and also handle pull request. the page also needs to be served over https since service worker can't be installed on http pages (unless it's localhost)

overall, i think it's just easier to wait and hope that writable-file gets implemented.

**Comment by caeserbala** [comment]
is there any update on this request ?

**Comment by jimmywarting** [comment]
filesaver can't never get support for completion callback
