### ISSUE TITLE
When I don't give the filename (optional), the name doesn't come from the file downloaded

### ISSUE THREAD

**Issue by alipsilv** [eligrey/FileSaver.js#439]
It's always "download" 
blob.name is undefined

**Comment by awerlang** [comment]
It's because there's no `name` property on `Blob` objects. Reference: https://developer.mozilla.org/en-US/docs/Web/API/Blob

You're probably refering to a `File` object, which come from an `<input type=file>` element.

I assume you're downloading a file from http through `fetch()`. Then check for response headers if a there's a name for the attachment. Otherwise you're out of luck.

**Comment by alipsilv** [comment]
yes, this "file" is generated as a blob type from http, and is directly passed to the function saveAs. This object has name as propertie

In the FileSaver there is a line where the file name can be taken from the blob "return new FileSaver(blob, name || blob.name || "download", no_auto_bom);". So I undestand that the library is waiting for a object with the  "name"  propertie defined. Is that correct?

**Comment by awerlang** [comment]
@alipsilv The function takes both File and Blob. `blob.name` is a bit misleading, as blobs don't have a `name` property. File's have. But calling the variable `file` would be misleading, too, because it can take a blob as well, files are blobs, but not all blobs are files. Refer to the link I shared the other day to learn more.

So "download" is the fallback name if you pass in a blob and no file name.
