### ISSUE TITLE
Possible to modify the dialog title?

### ISSUE THREAD

**Issue by tysenmoore-xse** [eligrey/FileSaver.js#480]
I am playing with the FileSaver from a page loaded through Electron.  Instead of downloading the file as it normally does in a browser it pops up a dialog box--which is nice.  However, the title of the dialog is, 
`blob:http://127.0.0.1:3030/0e3d7cd8-3858-415c-8c63-52038875a11b`.

As for my code, I am using your example:
```
blob = new Blob(["Hello, world!"],{
                    type: "text/plain;charset=utf-8"
                });
fileSaver.saveAs(blob, "hello world.txt");
```

Is there any way to modify the title of the dialog?  It appears `object_url` is defining this title, however, if I change `object_url` to "SomethingElse" after the call to `get_URL().createObjectURL(blob);` I then get a title of `http://127.0.0.1:3030/SomethingElse`.  I'd prefer to have a custom or empty title all together.  Is any of this possible?  It is not clear how much of this is under the control of the FileSaver versus Electron.

I did see this other question, https://github.com/eligrey/FileSaver.js/issues/101, but was not sure if this was still relevant.

Sorry for my ignorance in this area, still a little green.  Thanks for any time or help you can provide.

**Comment by jimmywarting** [comment]
Not possible with just FileSaver as it's right now.
also believe this is also out of the scope with FileSaver.js since it's targeted for browser only, Node.js and Electron is something completely different 

In electron you have to use the [dialog](https://github.com/electron/electron/blob/master/docs/api/dialog.md) and set a custom title, ask for a path of where to save something. then when u have the path you can start piping/writing a file to the destination. this involves more then just a blob, you need to use `buffer` & `fs` as well as the `FileReader` to accomplish this on your own

Maybe you can ask with electron if they can change the title of the save dialog to match the download attribute of `<a download="filename">` if the href is a blob url

**Comment by tysenmoore-xse** [comment]
Thanks for the quick response.  I was pleasantly surprised that Electron was hooking this API for me.  I was hoping I could game it.  However, I agree, I will likely have to revert to their native dialogs and perform the save operation.  Thanks again for the time.
