### ISSUE TITLE
What's up with the 2.0.1 release?

### ISSUE THREAD

**Issue by swftvsn** [eligrey/FileSaver.js#526]
Hi,

there's no mention in changelog what the new release is about? npm shows that 2.0.1 has been released. Was this an accident or did you just forgot to update changelog?

Thanks for the good work though!

**Comment by Koslun** [comment]
Think it was a case of forgetting to update changelog as the changes are indeed also just fixes so a 2.0.1 bump seems appropriate. Can see changes h[ere](https://github.com/eligrey/FileSaver.js/compare/2.0.0...3e46b730528fa34a82fcd97ba98d6e08c6f8eddf).

Looking at the specific changes there seems to be a lot of formatting changes obfuscating the actual changes but given that no issues have been created since release I'm just gonna give the release the benefit of a doubt and upgrade.

**Comment by NicolasCARPi** [comment]
Yes, please make a proper release :)

**Comment by tcsaddul** [comment]
Just to confirm this release now works in our app which also uses pdfmake.

**Comment by LeftBrainCreated** [comment]
Could recent changes cause the following error?

I read into this a bit, and it seems it could be a bug with npm, trying to confirm a file that hasn't completed. But I was curious if anyone else has run into this one.

0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Tools\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Tools\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'install',
1 verbose cli   'file-saver',
1 verbose cli   '--verbose' ]
2 info using npm@6.4.1
3 info using node@v10.15.1
4 verbose npm-session bc09b23a0268addb
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://registry.npmjs.org/file-saver 46ms (from cache)
8 silly pacote tag manifest for file-saver@latest fetched in 141ms
9 timing stage:loadCurrentTree Completed in 921ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 1165ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule file-saver@2.0.1 checking installable status
17 silly fetchPackageMetaData error for file-saver@file:file-saver@github:eligrey\FileSaver.js#e865e37af9f9947ddcced76b549e27dc45c1cb2e Could not install from "node_modules\jspdf\file-saver@github:eligrey\FileSaver.js#e865e37af9f9947ddcced76b549e27dc45c1cb2e" **as it does not contain a package.json file.**
18 timing stage:rollbackFailedOptional Completed in 0ms

**Comment by Ruffio** [comment]
I don't see any issue here. Please consider to close this

**Comment by swftvsn** [comment]
This is still an issue because the changelog has still not been updated - what has changed since 2.0.0?

**Comment by swftvsn** [comment]
Or if changelog is not used, please delete it (as we can’t rely on it anyway)

**Comment by NicolasCARPi** [comment]
Why is this issue closed? There is no 2.0.1 version on github and nothing in the changelog. Synchronize github and npm and then close the issue!

**Comment by Koslun** [comment]
@NicolasCARPi 
> There is no 2.0.1 version on github and nothing in the changelog. Synchronize github and npm and then close the issue!

We might already be on the same page but be clear, what is on github is what's been published to npm.

It's just that the changelog on github has not been updated for version `2.0.1` specifically.

**Comment by NicolasCARPi** [comment]
We've seen a number of malicious npm packages publishing updates on npm because the npm credentials were compromised. This is why I think it's important to have the github show that 2.0.1 is released, and what are the changes. There are several users on this issue asking for a simple update. I don't see why it would take months nor why it would be closed. I understand this project is (probably) maintained by volunteers, and everyone here is fine with some delays. Just don't close the issue @jimmywarting before tagging a commit and updating the changelog. Cheers :)

**Comment by jojobean13** [comment]
I'm trying to include jspdf in my project, which has file-saver 2.0.1 as a dependency, and this is causing an issue. I receive the following error: 
```
bower file-saver#2.0.1    ENORESTARGET No tag found that was able to satisfy 2.0.1
Additional error details:
Available versions in https://github.com/eligrey/FileSaver.js.git: 2.0.2, 2.0.0, 1.3.8, 1.3.7, 1.3.6, 1.3.4, 1.3.3, 1.3.2, 1.3.1, 1.3.0, 1.2.2, 1.2.1, 1.2.0
```
As stated, there is no 2.0.1 release in Github: https://github.com/eligrey/FileSaver.js/releases
