### ISSUE TITLE
Latest commit breaks file download in Chrome

### ISSUE THREAD

**Issue by nerbiker** [eligrey/FileSaver.js#624]
This recent commit (https://github.com/eligrey/FileSaver.js/commit/7a8ff3cc6ae717b6c7628b3c280a5c593c2206ee) has broken downloads in Chrome. 

When I use the script from Tampermonkey to download a text file a new tab opens with the text "downloading..." and the file is downloaded with the generic filename "download", ignoring the filename set in the script.

I'm using Chrome Version 80.0.3987.87 (Official Build) (64-bit) on a Mac running 10.14.3 (18D109)

Using a previous commit of FileSaver.js fixes the problem and my files are downloaded using the correct filename in the script.

**Comment by jonathanvanschenck** [comment]
Same problem.
Using the most recent commit (648ff96), I have some csv data which I try to save:
`js
let blob = new Blob(['some,data\n','more,data'], {type: "text/csv;charset=utf-8"});
saveAs(blob, "test.csv");
`
On Edge, the script works just fine, but when I run it on Chrome, I also get the popup window "about:_blank" with the text "downloading..." but instead of my "test.csv" file, I get prompted to save a generic "download" file which is un-openable.  
I stuck some console.log statements into FileSaver.js, and was able to isolate the issue between lines 158-169, but I don't have a good enough grasp of the code to know what really is going wrong here.

That all being said, if I roll back to commit 480d547 from Jan 25, the issue vanishes.

**Comment by jonathanvanschenck** [comment]
Actually, I think this is the same problem in #622

**Comment by paxter** [comment]
> That all being said, if I roll back to commit [480d547](https://github.com/eligrey/FileSaver.js/commit/480d547986765f6cd402702c5606f27be6fd810b) from Jan 25, the issue vanishes.

Thanks for the hint. I did that too and now it works in Chrome/Brave/other webkit browsers again. :)

**Comment by gabsoftware** [comment]
The issue is caused by commit 0a2e868b48b6d745a0f2b9bf448f9226925efcd0 (Rebuild dist).

That line: `var isWebKit = /AppleWebKit/.test(navigator.userAgent);` should not detect Chrome on Windows, but it does because Chrome user agent contains the string AppleWebKit!

Resolution: please use another way to detect WebKit inside a native macOS app.

**Comment by rajivshah3** [comment]
That's my bad, sorry 😞
