### ISSUE TITLE
dev.melobee.com

### ISSUE THREAD

**Issue by EtienneBruines** [eligrey/FileSaver.js#696]
What's up with `https://dev.melobee.com:4873` in the `package-lock.json` file?

It's not available (anymore?) and should probably be replaced by `registry.npmjs.org`

**Comment by eligrey** [comment]
I'll look into fixing this sometime this week

**Comment by imt-jaime** [comment]
I'm having issues during module installation. It seems that the project is developed under a private node package repository (dev.melobee.com:4873), all package-lock points to this [domain](https://github.com/eligrey/FileSaver.js/blob/9806041b0e800979dddabbaa1b5f6ce6952d7cd7/package-lock.json#L27).


```
npm ERR! npm ERR! code ENOTFOUND
npm ERR! npm ERR! syscall getaddrinfo
npm ERR! npm ERR! errno ENOTFOUND
npm ERR! npm ERR! network request to https://dev.melobee.com:4873/...
```

It might be in a VPN network however the private domain and port is being exposed (which is not secure at all). If package-lock is pointing to a private network, maybe the solution in this case is to ignore package-lock by using .gitignore or .npmignore files.
Usually this is not a good idea (for deterministic dependency trees). However, this possibility is actually impossible due to crashes during install.

**Comment by lopezvit** [comment]
> 



> I'm having issues during module installation. It seems that the project is developed under a private node package repository (dev.melobee.com:4873), all package-lock points to this [domain](https://github.com/eligrey/FileSaver.js/blob/9806041b0e800979dddabbaa1b5f6ce6952d7cd7/package-lock.json#L27).
> 
> ```
> npm ERR! npm ERR! code ENOTFOUND
> npm ERR! npm ERR! syscall getaddrinfo
> npm ERR! npm ERR! errno ENOTFOUND
> npm ERR! npm ERR! network request to https://dev.melobee.com:4873/...
> ```
> 
> It might be in a VPN network however the private domain and port is being exposed (which is not secure at all). If package-lock is pointing to a private network, maybe the solution in this case is to ignore package-lock by using .gitignore or .npmignore files. Usually this is not a good idea (for deterministic dependency trees). However, this possibility is actually impossible due to crashes during install.

@eligrey you can use this version: `"file-saver": "github:lopezvit/FileSaver.js#fix-package-lock-url"` if you want to have a fixed version of the dependencies.
