### ISSUE TITLE
Retrieve saved filename?

### ISSUE THREAD

**Issue by fernandojsg** [eligrey/FileSaver.js#75]
When you launch the file save dialog you can propose the file name to save it, but the user can change it after that. Is there any way to get this new saved filename?

Thank you very much.

**Comment by blurymind** [comment]
that is pretty awful. You should add a warning to the readme that it is not supported.

**Comment by jimmywarting** [comment]
what the user dose with the file afterwards is not any of your business? the web can not interact with the file afterwards anyway.

**Comment by blurymind** [comment]
What if you need to know the name of the file so you can display it. Or you
want to continually save changes to the file without having to navigate to
it every time. I guess to get that you would need to use fs library instead

**Comment by jimmywarting** [comment]
- you can't continually save changes to the same file
- you can't use fs since you don't have access to the filesystem
  -  so there is no way to read the filesystem - fs is a node.js thing only
- if you want to have that much control over the file (changing the file, store it for offline usage, etc) then you need to use some web storage layer like the sandboxed filesystem in Blink or the indexedDB or build some native application.

the alternativ is to wait and hope that https://github.com/WICG/native-file-system gets shipped to the browsers
